FROM gradle:7.3-jdk17 AS build

WORKDIR /app

COPY build.gradle settings.gradle ./
COPY gradle ./gradle

COPY src ./src

RUN gradle clean build -x test

FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

COPY --from=build /app/build/libs/cities-1.0.0.jar .

EXPOSE 8080

CMD ["java", "-jar", "cities-1.0.0.jar"]
